name: Block ads update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
  push:
    branches:
      - '**'

jobs:
  block_ads_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run the script
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_ACTOR_ID: ${{ github.actor_id }}
        run: python3 block_ads.py
